#set par(spacing: 1.5em)

*Background:* 
Freediving performance emerges from a tight coupling between underwater mechanics and breath-hold physiology.
Yet training practice and scientific discussion often treat performance as isolated personal bests (depth, time) rather than as a structured trade space. 
This work formulates freediving performance as a feasible region in the time–depth plane and studies its boundary as a performance frontier.

*Methods:* 
We model a dive as a depth trajectory $z(t)$ generated by thrust under buoyancy, weight, and drag, subject to instantaneous capacity constraints (e.g., force and power caps) and integrated physiological budgets (oxygen and, when relevant, carbon dioxide).
Mechanical demands are mapped to resource depletion using a budget-oriented metabolic proxy that incorporates baseline cost, force production, and mechanical power. 
Feasible dives are those that respect all constraints and budgets, and the performance frontier is defined as the boundary of this feasible set in the parameters space.
The frontiers are computed via constrained optimization, and the framework is instantiated by fitting effective parameters to real freediver data, including the author's own dive records.

*Results:* 
The model produces structured feasible regions in the total dive time $T$ v.s. maximum depth $D$ diagram and yields frontiers that agree qualitatively with observed dive clusters.
Binding-constraint analysis reveals depth-dependent regime transitions (e.g., capacity-limited versus budget-limited segments) and implies characteristic pacing and thrust-allocation patterns along frontier-optimal profiles.
Under this modeling, predicted feasibility boundaries and training levers are similar across entry-level and advanced divers, highlighting the usefulness of the frontier geometry.

*Implications:* 
The performance frontier provides a quantitative lens that unifies explanation and intervention: it can diagnose likely limiting mechanisms from dive data and suggest actionable training directions.
For example, reducing effective drag, shifting usable thrust capacity, improving effective efficiency terms, and shaping pacing/effort allocation.
More broadly, the framework offers a principled way to compare divers, disciplines, and training states using a computable boundary of feasibility rather than single-point performance metrics.
