#import "@preview/fancy-units:0.1.1": unit, qty

#import "../lib/macro.typ": O2, CO2, hfrac

= Introduction <sec:introduction>

Freediving is a sport of extremes performed under an unusually simple rule: *one breath in, and then everything*—motion, decision-making, and safety—must be paid for from finite internal resources.
The sport spans multiple disciplines with different performance axes (time in static apnea, distance in pool, and depth in open water), yet the governing constraints recur across them: hydrodynamics and buoyancy set the mechanical price of moving through water; propulsion is limited by force and power capacity; and physiological tolerance is bounded by oxygen availability, carbon dioxide accumulation, and the diver's ability to remain conscious and coordinated.

A practical challenge follows from this coupling: freediving performance is not naturally a single scalar quantity.
Even within a single discipline, a diver's outcome depends on pacing, profile choice, technique, and the interaction between mechanics and physiology.
As a result, much of freediving training remains experience-based: highly effective in the hands of good coaches, but difficult to generalize, quantify, or diagnose when progress stalls. This work asks whether we can turn the informal notion of "limits" into a quantitative object that is both explanatory and actionable.

#figure(
  image("../../images/depth-vs-dive.jpg"),
  caption: [
    *Dive Maximum Depth Across Sessions.* 
    This is a snapshot directly extracted from my #link("https://colab.research.google.com/drive/1Xaw7GBXP_hh8jce_TXNmNncG6fZMyukZ?usp=sharing")[Google Colab notebook] that tracks my personal freediving progress over time.
    Each dot is an individual dive ($y$-axis: max depth in meters) plotted over cumulative sessions ($x$-axis); marker size scales with dive duration and color encodes session progression. 
    The red stair-step curve traces the running personal best, highlighting the steady increase in achieved maximum depth over time.
  ],
  placement: top,
) <fig:depth-vs-dive>

#figure(
  image("../../images/depth-vs-time.jpg"),
  caption: [
    *Max Depth vs. Total Dive Time Across Sessions.* 
    Each point is a single dive, with maximum depth (m) plotted against total dive time (s); color encodes session number (earlier → later).
    The cloud shows the expected time-depth trade-off. 
    Short dives cluster near the surface while longer dives enable deeper maxima, with labeled STA points forming the long-duration, near-surface markers and DPV points marking assisted deeper dives at comparable or extended times.
  ],
  placement: top,
) <fig:depth-vs-time>

My motivation comes directly from personal dive logs. 
Since beginning freediving, I have recorded essentially all dives as depth time series, then visualized progress using simple summaries. 
Two plots are particularly revealing.
The first tracks maximum depth across sessions and shows the expected staircase structure of gradual progress punctuated by personal bests (@fig:depth-vs-dive). 
The second is a time–depth plot: for each dive, total dive time $T$ versus maximum depth $D$ (@fig:depth-vs-time). What is striking is not only that the points form a coherent region, but that the boundary appears structured: deeper dives tend to require longer total times, but not arbitrarily so, and "outliers" (e.g., assisted dives) occupy distinct locations.
Moreover, improvements in one area of training can shift performance in others, suggesting a shared underlying constraint geometry rather than independent skills.

I began to view these plots as a map of feasibility.
Instead of asking "What is my maximum depth?" or "What is my maximum time?", a more revealing question is: *What combinations of total time and depth are feasible under the coupled constraints of mechanics and physiology?* If such a feasible set exists, then its boundary (what divers informally call "the limit") should also exist as a mathematically definable object.
This motivates the central construct of this thesis: a freediving *performance frontier* in the $(T, D)$ plane.

This thesis proposes an end-to-end quantitative framework that
(i) formally defines the time-depth feasible set,
(ii) derives it from a reduced but explicit model of underwater motion and resource usage, 
(iii) computes frontier envelopes via optimization, and
(iv) instantiates the framework with data from real freedivers.
At a high level, we model a dive as a depth profile in time generated by a thrust/force history under buoyancy, weight, and drag. 
Feasibility is determined by instantaneous limits (e.g., force and power caps) together with integrated physiological budgets.
To connect mechanics to physiology, we formulate metabolic models that map mechanical power and force production to oxygen consumption and carbon dioxide accumulation.

Within this framework, the performance frontier naturally splits into two complementary envelopes: a *fast frontier* (minimum feasible time for a given depth) and a *slow frontier* (maximum feasible time for a given depth). 
These envelopes are not merely descriptive curves.
Because they arise from constrained optimization, they yield both predictions and diagnostics: they identify which constraints bind at which depths and pacing regimes, and they imply structured optimal profiles that can be compared against observed diver behavior.

The main contributions of this work can be summarized as four pillars:

+ *Formal Frontier Formulation.*
  To our knowledge, this is the first framework that formulates a freediving performance frontier in formal terms and derives it using quantitative tools spanning hydrodynamics, forces and motion constraints, and resource-bounded physiological modeling.

+ *Data-Tethered Instantiation.*
  The framework is not purely theoretical: we show how to calibrate and fit effective model parameters using real freediver data, yielding diver-specific feasible regions and frontier predictions.

+ *Mechanistic Diagnostics via Constraint Switching.*
  The frontier is used as a diagnostic instrument: observed phenomena in freediving performance are explained through binding-constraint analysis and regime transitions along the frontier.

+ *Actionable Training Implications.*
  The model not only explains existing behavior but also suggests training levers—reducing effective drag, shifting usable thrust capacity within force/power limits, improving effective efficiency terms, and shaping pacing/effort allocation—in ways that align with experience-based heuristics discussed later in the thesis.

Scope is intentionally focused.
We model mechanics, resource bookkeeping, and profile optimization at a level appropriate for feasibility analysis and training interpretation.
We do not attempt to model equalization technique, detailed psychological factors, or higher-order physiological mechanisms (e.g., spleen contraction, detailed blood-shift dynamics) except insofar as their net effects can be absorbed into effective parameters or treated as unmodeled variability.
The objective is a disciplined systems model that is expressive enough to explain and guide, without claiming to simulate the full biological complexity of breath-hold diving.

The remainder of the thesis is organized as follows.
@sec:related-work reviews prior work on breath-hold physiology, freediving training effects, and performance frontiers in other sports.
@sec:theory-primers introduces definitions, assumptions, and the reduced mechanical and metabolic models used throughout.
@sec:performance-frontier-td formalizes the time–depth feasible set and derives fast and slow frontiers via optimization.
Finally, @sec:applications-and-discussions instantiates the framework on real diver data, interprets the resulting frontiers and binding constraints, and discusses practical implications for training and performance.

#pagebreak()

= Related Work <sec:related-work>

== Physiology in Freediving <sec:rw-physiology>

Breath-hold freediving sits at an unusual intersection of *gas exchange constraints*, *circulatory control*, and *environmental pressure effects*. A useful big-picture framing is that performance and safety are jointly shaped by (i) the size and accessibility of the body's usable oxygen reserve, (ii) the rate at which that reserve is spent during phases of locomotion and recovery, and (iii) depth-dependent risks and constraints that do not appear in surface sports. Broad, integrative reviews summarize these interacting mechanisms and the known failure modes (e.g., hypoxic blackout, lung squeeze, nitrogen-related effects) in humans @lindholm2009physiology @ferretti2001extreme @patrician2021breath.

A central "built-in control system" for economy is the diving response: stereotyped bradycardia with peripheral vasoconstriction that tends to preserve oxygen delivery to the heart and brain while reducing perfusion to less immediately critical tissues. 
This response is not a single knob; its onset and magnitude depend on factors such as facial immersion, apnea duration, temperature, and training status, and its expression coexists with competing demands from exercise and stress.
Mechanistically oriented treatments (including animal physiology, where many pieces are experimentally accessible) emphasize that this reflex is best understood as a survival-preserving control policy whose emergent effect is often to reduce effective oxygen burn-rate under apnea, especially in resting or low-motion conditions @michael2013mammalian.

These physiological perspectives motivate two modeling choices used later in this manuscript: 
(i) to treat oxygen usage as a *budgeted resource* rather than a directly observable scalar, and
(ii) to allow "baseline" consumption and effective reserve size to reflect context-dependent physiology rather than being interpreted as universal constants.
In other words, the basal term in an oxygen-consumption proxy model should be read as a *conditioned* metabolic rate under apnea/immersion (not the land-based resting metabolic rate), and the total usable reserve should be treated as model-dependent because different studies operationalize and estimate the compartments differently @ferretti2001extreme @lindholm2009physiology.

== Training Effects in Freediving <sec:rw-training-effects>

Training research in freediving spans "skill-like" improvements (relaxation, pacing, technique, psychological tolerance) and physiological adaptations that plausibly alter both the usable oxygen reserve and its spending profile. 
A practical entry point is apnea-table training, where protocols intentionally manipulate #O2 and #CO2 stress to target distinct constraints on breath-hold duration. 
For example, controlled comparisons of #O2\- and #CO2\-table style protocols in novices suggest that baseline capacity markers (e.g., lung volumes, resting oxygenation proxies) and the ability to tolerate progressive hypoxia/hypercapnia are separable contributors to apnea performance, and that different protocols can bias which component improves @declercq2024dive.

Beyond single-protocol studies, meta-analytic work indicates that multiple apnea-training modalities can produce substantial improvements in maximal static apnea time, while also highlighting heterogeneity in participant background, protocol details, and outcome measures—making it difficult to claim a single "best" intervention across populations @massini2022training. 
Pilot intervention studies similarly report cardiorespiratory and performance-related changes with static apnea training, consistent with the idea that training can shift the economy and tolerance landscape, even if study sizes and designs limit strong causal claims @bezruk2024effect.

For the purposes of a performance-frontier model, the key takeaway is not that any one protocol is optimal, but that training plausibly acts through *multiple levers* that map onto model components: 
(i) increasing effective reserve (compartment utilization and accessibility), 
(ii) decreasing basal spending under apnea/immersion (via enhanced diving response and relaxation), and 
(iii) reducing locomotion cost per unit distance (technique and hydrodynamics). 
This motivates treating fitted parameters as *athlete- and condition-specific* summaries of these interacting adaptations, rather than as fixed biological constants.

== Performance Frontier in Other Sports <sec:rw-frontier-other-sports>

The idea of a "performance frontier" is well established across sports science, typically as a boundary separating sustainable from unsustainable effort, or as an optimal trade-off curve between competing performance objectives. 
These frontiers are valuable because they support both diagnosis ("which limiter dominates?") and prescription ("which training shifts the boundary most efficiently?").
The freediving setting differs in its physics and physiology, but it benefits from the same conceptual toolkit.

A canonical example is the *power–duration* (or speed–duration) boundary, where a hyperbolic relationship links sustainable output to time-to-exhaustion and introduces a fatigue-related asymptote. 
A foundational work formalized this relationship for muscular work, and later syntheses and modern treatments framed "critical power" as a practical fatigue threshold with diagnostic value for endurance performance @monod1965work @poole2016critical. 
Closely related are threshold-style frontiers based on lactate kinetics, where maximal lactate steady state (MLSS) is treated as a boundary between quasi-steady physiological control and progressive metabolic instability @billat2003concept.

In explosive and mixed sports, frontiers appear as *force–velocity* and *power–velocity* profiles. 
These frameworks treat performance as constrained by neuromuscular capacity and mechanics, and they enable optimization by shaping the athlete's profile toward an "optimal" configuration for a task (e.g., jumping) rather than only increasing peak force or peak power @samozino2012optimal. 
More generally, mechanistic movement analyses provide the template for decomposing performance into interpretable components that can be trained differentially @gonzalez2010movement.

Frontier thinking also appears in training systems as an optimization problem: how to allocate training intensity and volume to push the boundary without exceeding recoverable load. 
Work on quantifying intensity distribution (e.g., polarized vs. threshold-heavy approaches) and on the scientific rationale for peaking/tapering illustrates how empirical practice can be formalized into boundary-aware training decisions @seiler2006quantifying @padilla2003scientific. 
Finally, environmental adaptation research (heat and altitude) provides examples of how external constraints reshape physiological boundaries and how interventions selectively move them @levine1997living @periard2015adaptations.

These traditions justify the methodological stance taken in this manuscript: construct an explicit frontier model by combining 
(i) physics-based external demands with
(ii) resource-budget constraints, 
then interpret deviations and parameter shifts as actionable signatures of technique, physiology, and training history.

== Energetics and Hydrodynamics <sec:rw-energetics-hydro>

Hydrodynamics and locomotion energetics form the mechanical backbone of any quantitative freediving model: they determine how forces and power scale with speed, posture, and equipment, and therefore how "mechanical effort" converts into budget spending. 
Swimming research provides a mature set of measurement and modeling tools for
(i) drag characterization (towing, velocity-decay methods, and computational fluid dynamics, CFD),
(ii) decomposition of drag components and posture effects, and 
(iii) efficiency- and cost-based performance summaries.

Passive drag and drag-coefficient estimation have been studied using both analytical procedures and numerical simulation, supporting the practice of modeling resistive force as scaling approximately with $v^2$ in relevant regimes and lumping morphology and posture into an effective coefficient/area surrogate @barbosa2018assessment. 
CFD analyses further show that posture changes can produce large, systematic differences in drag coefficients during submerged gliding, reinforcing that "streamlining" should be treated as a quantitatively meaningful state rather than a qualitative cue @marinho2009gliding @cortesi2015headpos.
Depth also matters: wave-drag effects dominate near the surface and diminish with submergence, producing a depth-dependent drag reduction that saturates beyond moderate depth in streamlined gliding conditions @novais2012depthdrag.

On the energetics side, classic and modern treatments connect mechanical work, hydrodynamic resistance, and metabolic cost through gross efficiency and technique-dependent propulsion mechanics @toussaint1990mechanical @toussaint1994energetics @zamparo2020energy. 
Empirical work on propulsion contributions (arms vs legs) and tethered-force relationships provides additional bridges from measurable mechanics to performance outcomes @deschodt1999relative @moroucco2011relationship @moroucco2015relative.

Equipment effects are especially relevant for freediving disciplines (bi-fins vs monofin). Studies of fin swimming at the surface quantify meaningful reductions in energy cost and changes in efficiency as a function of fin characteristics, supporting the need to treat "propulsion mode" as a parameter regime rather than a minor perturbation @zamparo2006economy.
Most directly aligned with competitive dynamic apnea, recent measurements report energy cost per unit distance and partition aerobic/anaerobic contributions in DYN, highlighting that oxygen sparing can be as important as minimizing mechanical cost and that fin choice can change the energetic landscape measurably @vinetti2025apneaenergetics.

Finally, theoretical work on breath-hold diving locomotion emphasizes the energetic importance of alternating active swimming with prolonged glides under buoyancy and drag constraints, and provides a mechanics-first precedent for optimizing transit speed and glide allocation under a metabolic budget @trassinelli2016breathhold.

= Theory Primers <sec:theory-primers>

== Definitions, Scope and Assumptions <sec:definitions-scope>

We analyze a set of breath-hold dives recorded by a dive watch as time series of
depth.
For each dive, let $z (t)$ denote depth (meters), with $z = 0$ at the free surface and positive downward.
We define two primary observables:

- *Total Dive Time* $T$:
  For depth disciplines, $t=0$ is the last moment on the surface before continuous descent (i.e., the start of submergence), and $T$ is the first moment the diver returns to the surface at the end of the ascent.
  For static apnea (STA), $t=0$ is the start of the breath-hold at the surface and $T$ is the end of apnea (first recovery breath).
  In practice, watch depth signals may jitter near the surface, but the conceptual definition remains "submerge to resurface" (depth) or "start-to-end of apnea" (STA).

- *Maximum Depth* $D$: $D := max_(t) z(t)$.
  For STA dives, $D = 0$ by construction.

An example profile with these definitions marked is shown in @fig:example-profile.

#figure(
  image("../../images/example-profile.pdf"),
  caption: [
    *Example Dive Profile and Definitions.*
    The depth trace $z(t)$ is shown with $z = 0$ at the surface (positive downward).
    Total dive time $T$ spans submerge-to-resurface, and maximum depth $D$ is the deepest point of the profile.
  ],
  placement: top,
) <fig:example-profile>

*Scope of Dives.*
We focus on depth-session and static-session dives only: CWT/CWTB/FIM and STA.

*Failure Criterion.*
In a maximal dive, the attempt ends when the first limiting factor is reached.
We model this with resource budgets and define the performance frontier as dives that saturate at least one budget.
In this exploratory analysis, we track the two most quantifiable resources in freediving literature: usable #O2 and #CO2 tolerance.
Formal budget and effort definitions are given later in @sec:metabolic-budgets.

*Noise and Unmodeled Variability.*
Throughout, "noise" refers to all unmodeled variables that affect observed performance but are not explicitly represented in the equations: environmental conditions (waves, current, temperature), equipment configuration (suit thickness, ballast, fin choice), day-to-day physiological state, technique variability, and measurement error.
We treat these factors as perturbations absorbed into effective parameters (e.g., drag, efficiency, budgets) rather than as additional modeled state variables.
In other words, the model aims to explain the dominant structure of the time--depth envelope, while residual scatter is attributed to noise.

== Forces, Kinematics, and Constitutive Laws <sec:forces-kinematics>

We model a breath-hold diver undergoing *purely vertical* motion in quiescent seawater of uniform properties.
The vertical axis is taken positive downward.
Let depth be $z(t)$ with $z = 0$ at the free surface, and velocity $v(t) = dot(z)$ (positive downward).
We neglect horizontal drift, surface waves, currents, and unsteady ambient flow structures.
Seawater density $rho_w$ and gravitational acceleration $g$ are treated as constants, with representative values $rho_w approx$ #qty[1025][kg/m^3] and $g approx$ #qty[9.81][m/s^2].

=== Equation of Motion <sec:eq-motion>

The vertical equation of motion (positive downward) is

$
m dot(v) = F_"mech" (t) + m g - B(z) - F_"drag" (v)
$ <eq:eom>

where:

- $F_"mech" (t)$ is the self-generated thrust or traction with fins (CWT/CWTB), without fins (CNF), or via rope pulling (FIM).
  It is positive when pushing downward (e.g., fins during descent) and negative when pulling upward (ascent).

- $m g$ is the weight (downward).

- $B(z) = rho_w g V_"disp" (z)$ is the buoyant force magnitude (upward).

- $F_"drag" (v)$ is the hydrodynamic drag opposing motion.

=== Buoyancy and Displaced Volume <sec:buoyancy-displaced>

We decompose the displaced volume into three parts:

$
V_"disp" (z) = V_"const" + V_"suit" (z) + V_"gas" (z)
$ <eq:vdisp>

Here $V_"const"$ collects the near-incompressible body+tissue+equipment volume *at depth* (interpreted as the asymptotic displaced volume as $z -> oo$ when suit compression is complete and pulmonary gas is fully compressed).
The optional $V_"suit" (z)$ accounts for wetsuit/foam compressibility.
The compressible gas volume $V_"gas" (z)$ follows Boyle's law:

$
V_"gas" (z) = V_("gas", 0) P_0 / P(z),
quad
P(z) = P_0 + rho_w g z
$ <eq:boyle>

where $V_("gas", 0)$ is the *total compressible gas volume at the surface* (lungs + communicating air spaces such as mask and other air pockets, modeled as an effective single reservoir).
Surface pressure is $P_0 approx$ #qty[1013.25][hPa].
Define the pressure length

$
L_p := P_0 / (rho_w g)
$ <eq:Lp>

so that $P(z) = rho_w g (L_p + z)$ and $V_"gas" (z) = V_("gas", 0) L_p/(L_p + z)$.
For seawater, $L_p approx$ #qty[10.1][m].

In subsequent analysis, we absorb the suit compressibility term into the constant displaced-volume term $V_"const"$.

// *Suit Compressibility.*
// A simple parametrization is a one-parameter decay:
//
// $
// V_"suit" (z) = V_("suit", oo) + (V_("suit", 0) - V_("suit", oo)) (P_0 / P(z))^(n_"suit")
// $ <eq:vsuit>
//
// where $V_("suit", 0)$ and $V_("suit", oo)$ are the suit volumes at surface and infinite depth, respectively, and $n_"suit"$ controls the compression rate.
// Keeping an explicit $V_"suit" (z)$ makes subsequent algebra and closed-form expressions noticeably messier.
// In most practical operating ranges, the remaining suit contribution behaves like a near-constant buoyancy offset, so we absorb the deep-limit suit volume into the constant displaced-volume term:
//
// $
// V'_"const" := V_"const" + V_("suit", oo)
// $ <eq:Vconst-reassign>
//
// With this convention, we proceed by omitting the explicit suit term and keep the same Boyle gas model @eq:boyle and pressure length @eq:Lp (i.e., we use $V'_"const"$ and write it as $V_"const"$ for notational simplicity in later sections).

=== Drag <sec:drag>

We use the standard quadratic drag law written in a numerically stable form:

$
F_"drag" (v) = k v abs(v),
quad
k := 1/2 rho_w C_d A
$ <eq:drag>

where $C_d$ is the drag coefficient and $A$ is the effective frontal cross section area.
A representative range is $C_d approx$ 0.9--1.1 and $A approx$ 0.08--0.12 #unit[m^2] @barbosa2018assessment.
This lands $k$ roughly in the range $k approx$ 30--60 #unit[N/(m/s)^2] for typical human freedivers.
In this work, we treat $C_d$ as approximately fixed for a given configuration, while interpreting improvements in streamlining and body position as changes in the effective area $A$, which can be trained and optimized.

// *Implementation Note.*
// For stiff integrators and near $v = 0$, a smooth surrogate $F'_"drag" (v) = k v sqrt(v^2 + epsilon^2)$ with $epsilon approx #qty[0.02][m/s]$ can prevent numerical chatter in optimization and terminal-speed inversions.

== Re-parameterization and Nondimensionalization <sec:reparam-nondim>

This section re-expresses the vertical dynamics in terms of a small set of physically interpretable and easily measurable parameters.
We assume the explicit suit term has been absorbed into the constant displaced-volume term as described previously, and proceed using $V_"const"$ and the Boyle gas model @eq:boyle.

=== Large-Depth Net Load <sec:large-depth-net-load>

Define the asymptotic (large-depth) net load

$
Delta F_oo := m g - rho_w g V_"const"
$ <eq:DeltaF-oo>

which is the weight minus asymptotic buoyancy.

Interpretation:

- If $Delta F_oo > 0$, the diver is (slightly) negative at great depth; a finite free-fall terminal speed exists.
- If $Delta F_oo = 0$, the diver is neutrally buoyant as $z -> oo$; deep free-fall tends to zero speed.
- If $Delta F_oo < 0$, the diver is positive at great depth; pure free-fall descent is not possible.

=== Neutral Depth $z_n$ <sec:neutral-depth>

Define $z_n$ as the depth where weight equals buoyancy under the depth-compressed gas model:

$
m g = B(z_n) = rho_w g (V_"const" + V_"gas" (z_n))
$ <eq:zn-def>

Equivalently,

$
Delta F_oo = rho_w g V_"gas" (z_n).
$ <eq:zn-DeltaF>

Writing @eq:boyle as $V_"gas" (z) = V_("gas", 0) L_p/(L_p + z)$ yields

$
1 + z_n/L_p = (rho_w g V_("gas", 0)) / (Delta F_oo),
quad "equivalently" quad
z_n = L_p ((rho_w g V_("gas", 0)) / (Delta F_oo) - 1).
$ <eq:zn-link>

This identity shows how the neutral depth couples surface compressible gas volume $V_("gas", 0)$ and deep load $Delta F_oo$.
At fixed $V_("gas", 0)$, adding weight increases $Delta F_oo$ and shifts $z_n$ shallower,
while removing weight decreases $Delta F_oo$ and shifts $z_n$ deeper.
Typical values of $z_n$ for freedivers per AIDA guidance are $approx$ 10--20 #unit[m] for shallower dives @aida3manual and dives as deep as #qty[60][m] @aida4manual.

=== Deep Terminal Velocity <sec:deep-terminal-velocity>

When $Delta F_oo > 0$ and thrust is zero ($F_"mech" (t) = 0$), define the deep terminal speed by balancing deep load with quadratic drag @eq:drag:

$
v_oo := sqrt((Delta F_oo) / k)
$ <eq:v-oo>

Equivalently,

$
Delta F_oo = k v_oo^2,
quad
k = (Delta F_oo) / v_oo^2.
$ <eq:k-from-voo>

The quantity $v_oo$ should be interpreted as the *asymptotic free-fall (glide) speed* that would be approached at sufficiently large depth, where buoyancy has nearly reached its deep limit and the net load approaches $Delta F_oo$.
It is not the average descent speed of a full constant-weight dive, since real dives include an active descent phase above $z_n$, a transition region near $z_n$, and a turn plus active ascent.

Human breath-hold dive profiles are often discussed at characteristic vertical speeds around #qty[1][m/s] in the literature @bosco2007breath @patrician2021breath.
These values are consistent with using $v_oo$ on the order of $v_oo approx$ 0.8--1.2 #unit[m/s] as a practical scale for constant-weight-style glides in a well-weighted diver.

=== Re-parameterized Equation of Motion <sec:eom-reparam>

Define the net load (downward-positive) as $Delta F (z) := m g - B (z)$.
With suit absorbed into $V_"const"$ and Boyle-compressed gas @eq:boyle, we obtain the compact form

$
Delta F (z)
= Delta F_oo (z - z_n)/(L_p + z)
= k v_oo^2 (z - z_n)/(L_p + z),
$ <eq:W-voo>

where $Delta F_oo := m g - rho_w g V_"const"$, $z_n$ is the neutral depth @eq:zn-link,
and $Delta F_oo = k v_oo^2$ by @eq:k-from-voo.

Substituting @eq:W-voo and quadratic drag @eq:drag into the vertical equation of motion @eq:eom gives

$
m dot(v)
= F_"mech" (t)
+ k v_oo^2 (z - z_n)/(L_p + z)
- k v abs(v).
$ <eq:eom-reparam>

Equivalently,

$
m dot(v)
= F_"mech" (t)
+ k [ v_oo^2 (z - z_n)/(L_p + z) - v abs(v) ].
$ <eq:eom-reparam-k>

This representation is governed by three physically interpretable parameters:
the deep load $Delta F_oo$ (equivalently $v_oo$), the neutral depth $z_n$, and the pressure length $L_p$.
All remaining depth dependence enters only through the ratio $(z - z_n)/(L_p + z)$.

=== Nondimensionalization <sec:nondimensionalization>

The re-parameterized equation of motion @eq:eom-reparam-k admits a natural nondimensional form using $v_oo$ and $L_p$ as characteristic scales.
Define the dimensionless variables

$
tilde(z) := z / L_p,
quad
tilde(z)_n := z_n / L_p,
quad
tilde(v) := v / v_oo,
quad
tilde(t) := (v_oo / L_p) t.
$ <eq:nondim-vars>

With these definitions,

$
dot(v) = (v_oo^2 / L_p) (dif tilde(v)) / (dif tilde(t)).
$ <eq:vdot-scale>

Substituting @eq:nondim-vars and @eq:vdot-scale into @eq:eom-reparam-k gives

$
m (v_oo^2 / L_p) (dif tilde(v)) / (dif tilde(t))
=
F_"mech" (t)
+ k v_oo^2 (tilde(z) - tilde(z)_n)/(1 + tilde(z))
- k v_oo^2 tilde(v) abs(tilde(v)).
$

Dividing through by the characteristic force scale $k v_oo^2 = Delta F_oo$ yields the dimensionless equation

$
(m / (k L_p)) (dif tilde(v))/(dif tilde(t))
=
tilde(F)_"mech" (tilde(t))
+ (1 - (1 + tilde(z)_n)/(1 + tilde(z)))
- tilde(v) abs(tilde(v)),
$ <eq:eom-nondim>

where the dimensionless control input is

$
tilde(F)_"mech" (tilde(t)) := (F_"mech" (t)) / (Delta F_oo).
$ <eq:F-tilde>

The single remaining dimensionless inertia parameter is

$
lambda := m / (k L_p),
$ <eq:lambda>

so that the nondimensional form may be written as

$
lambda (dif tilde(v))/(dif tilde(t))
=
tilde(F)_"mech" (tilde(t))
+ (1 - (1 + tilde(z)_n)/(1 + tilde(z)))
- tilde(v) abs(tilde(v)).
$ <eq:eom-nondim-lambda>

In the quasi-steady limit, acceleration is small compared to the dominant force balance between thrust, buoyancy, and drag, and the dynamics reduce to an instantaneous force balance on each segment of motion.

== Physiological Model and Budgets <sec:phys-model-budgets>

=== #O2 and #CO2 <sec:o2-co2>

Following AIDA manual conventions @aida4manual, we model freediving performance through *integrated resource bookkeeping* over a dive as shown in @fig:o2-and-co2-budget.
The attempt terminates when the first limiting factor is reached.
In this exploratory analysis we track two physiological resources: usable #O2 and #CO2 tolerance.

#figure(
  image("../../images/example-budget.pdf"),
  caption: [
    *Conceptual Framework for Integrated Resource Bookkeeping in Freediving.*
    The figure illustrates the dual-constraint model where dive time ($T$) is determined by the first of $E_#O2$ or $E_#CO2$ to reach 1.
    *Top Left (#O2 Budget):* Represents the usage of usable oxygen store ($R_#O2^"total"$) from zero toward the total store, influenced by basal metabolic rates and work-dependent consumption.
    *Top Right (#CO2 Tolerance):* Illustrates the accumulation of metabolic #CO2 toward an effective physiological tolerance threshold ($R_#CO2^"total"$), serving as a proxy for the hypercapnic urge-to-breathe.
    *Bottom (Active Limiter Dive Profiles):* A state-space representation showing how different diver profiles interact with these constraints.
    Dive Profile A represents a #CO2\-limited dive, where the tolerance threshold is reached while #O2 remains slack ($E_#O2 < 1$).
    Dive Profile B represents a #O2\-limited dive, where the oxygen budget saturates while #CO2 remains slack ($E_#CO2 < 1$).
  ],
  placement: top,
) <fig:o2-and-co2-budget>

*Oxygen Budget.*
Let $R_#O2^"total"$ denote the *usable* oxygen store available for the dive, not the total body oxygen content.
For example, blackout can occur well before (around 45% $"SaO"_2$) complete depletion of total body oxygen due to compartmental accessibility limits and physiological prioritization.

Conceptually, usable #O2 is drawn from lung gas, blood (hemoglobin-bound), and muscle (myoglobin), with the diving response (bradycardia and peripheral vasoconstriction) effectively reducing the depletion rate by prioritizing oxygen delivery to critical organs.
We treat these mechanisms as captured implicitly by the basal consumption rate and the effective budget parameter rather than modeling compartmental transport explicitly.

A well-known exception in freediving is *shallow-water blackout*, where risk can increase near the surface due to rapid changes in gas partial pressures during ascent despite continued total oxygen consumption.
In the present model we do not represent such depth-dependent resource *state changes*.
Dives are assumed to terminate due to resource depletion or intolerance under the integrated bookkeeping constraints defined below, and partial-pressure dynamics are treated as out of scope.

*Carbon Dioxide Tolerance.*
Let $R_#CO2^"total"$ denote an *effective* #CO2 tolerance budget, representing a physiological threshold rather than a literal storage capacity.
Carbon dioxide is produced continuously by metabolism and is buffered in blood and tissues, while discomfort and termination are mediated primarily through chemoreception and acid--base balance (e.g., pH changes) rather than absolute #CO2 volume alone.
Accordingly, $R_#CO2^"total"$ should be interpreted as a compact proxy for the subject's tolerance to hypercapnia and associated urge-to-breathe, folded into an integrated budget for modeling convenience.

*Role of STA in Calibration.*
Static apnea (STA) is included not as a motion-modeled dive, but as a calibration anchor for the basal consumption regime.
In STA, $F_"mech" (t) = 0$ and the vertical motion model is not used.
Instead, STA observations constrain the baseline metabolic term (and, depending on modeling choices, may also inform effective budgets) used in depth disciplines.
The resulting oxygen values are examples under a chosen normalization of usable oxygen, not direct measurements of absolute stores.

=== Metabolic Rate Model <sec:metabolic-rate-model>

This subsection specifies how mechanical effort maps to instantaneous resource usage.
The goal is not a microscopic muscle model; it is a *budget-compatible* proxy that
(i) respects sign (no "negative oxygen burn"),
(ii) assigns cost to force production even when $v approx 0$, and
(iii) produces realistic magnitudes when evaluated against human limits reported in
swimming and breath-hold literature.

We model the instantaneous oxygen consumption rate as

$
dot(V)_#O2
=
dot(V)_(#O2,"rest")
+ alpha (abs(F_"mech" (t)) / F_"ref")^p
+ beta P_"mech" (t),
$ <eq:odot>

where

- $dot(V)_(#O2,"rest")$ is a basal oxygen consumption rate,
- $alpha (hfrac(abs(F_"mech" (t)), F_"ref"))^p$ is a force-production overhead term, and
- $beta P_"mech" (t)$ is a mechanical power cost term.

*Basal (Non-Locomotor) Cost.*
Even under strong relaxation and an established diving response, apnea is not free: organs continue to consume oxygen and postural muscles perform small amounts of work.
Reported lowest whole-body oxygen uptake during static breath-hold in trained divers is on the order of #qty[0.20][L/min] @fitz2018breath, corresponding to a few #unit[mL/s].
We model this with a constant basal term $dot(V)_(#O2,"rest")$, typically on the order of $dot(V)_(#O2,"rest") approx$ 2.5--#qty[4][mL/s] in trained divers, treated as calibratable from static apnea (STA) measurements.

*Force-Production Overhead.*
Muscles also expend energy to produce force even when external mechanical work is small, such as during hovering, strong bracing, or slow motion with large thrust.
Recent calorimetric evidence shows a nonlinear scaling of metabolic cost with isometric torque, with an exponent around $p approx$ 1.6 @muralidhar2023metabolic.
We adopt this idea as a parsimonious overhead term.

The reference force $F_"ref"$ is a global normalization scale shared across divers and protocols.
Measured 30 s fully-tethered front crawl forces show mean forces of $approx$ 74--99 #unit[N] (female–male) @moroucco2015relative, making

$
F_"ref" approx #qty[100][N]
$ <eq:Fref-default>

a convenient and interpretable choice.

The coefficient $alpha$ is diver-specific and represents the additional oxygen rate incurred when producing thrust of order $F_"ref"$ at very low speed.
It captures technique, neuromuscular efficiency, and how costly force production is for the individual diver.

*Mechanical Power Cost via Gross Efficiency.*
When the diver produces *positive* mechanical power against the water, metabolic demand rises.
The mechanical power is defined as

$
P_"mech" (t) := (F_"mech" (t) dot.op v(t))_+,
quad
(dot.op)_+ := max(dot.op, 0).
$ <eq:Pmech-def>

To convert $P_"mech" (t)$ into an oxygen consumption rate, we introduce an *effective gross efficiency*
$eta$ that captures all losses from metabolic energy to external mechanical output, including muscle
efficiency, transmission losses, and fin–fluid propulsion losses.
Direct measurements in front crawl @toussaint1994energetics report gross efficiency approximately $eta approx$ 0.05--0.095.

with substantial dependence on speed and technique, and fins can further shift economy and efficiency
depending on fin size and stiffness.

Let $e_#O2$ denote the energy equivalent of oxygen uptake.
A commonly used single-value conversion in exercise physiology is

$
e_#O2 approx #qty[20.1][J/mL].
$ <eq:eO2>

With these conventions, the oxygen cost associated with positive mechanical power is

$
hfrac(P_"mech" (t), (eta dot.op e_#O2)).
$ <eq:o2-power>

Matching this to the linear term $beta P_"mech" (t)$ in @eq:odot implies

$
beta = hfrac(1, (eta dot.op e_#O2)).
$ <eq:beta-def>

Typical values of $beta$ are on the order of $beta approx$ #qty[0.7][mL/J].

*#CO2 Generation.*
Carbon dioxide generation is modeled as proportional to oxygen consumption:

$
dot(V)_#CO2 = gamma dot(V)_#O2,
$ <eq:cdot>

where $gamma$ is an effective conversion factor.
For mixed substrate use under apnea, a representative range is $gamma approx$ 0.85--0.95.

The parameter $gamma$ should be interpreted as an integrated proxy that folds buffering,
substrate mix, and chemoreceptor sensitivity into a single effective coefficient.

=== Instantaneous Force and Power Capacity Constraints <sec:instant-capacity-constraints>

The integrated budgets above limit what can be sustained over the entire dive.
However, the control input $F_"mech" (t)$ is also limited *instantaneously* by neuromuscular capacity and by how effectively propulsion can transmit force to the water.
Without explicit instantaneous limits, a model can generate physically impossible short-duration thrust spikes.

We impose instantaneous capacity ceilings:

$
abs(F_"mech" (t)) <= F_"mech"^"max",
quad
P_"mech" (t) <= P_"mech"^"max".
$ <eq:cap-constraints>

The force ceiling $F_"mech"^"max"$ limits how hard the diver can push or pull at any instant,while the power ceiling $P_"mech"^"max"$ prevents unrealistically large force at high speed.
Together, these constraints define the feasible control space before integrated resource budgets are even considered.

*Empirical Scale for Thrust.*
A useful anchor comes from fully-tethered swimming, where force can be measured directly.
In 30 s maximal tethered front crawl tests, reported peak forces are on the order of
a few hundred newtons ($approx$ 220--325 #unit[N], female–male), with mean forces around
74--99 #unit[N] @moroucco2015relative.
These values place $F_"mech"$ in the correct physiological range:
tens of newtons correspond to relaxed cruising, while hundreds of newtons correspond
to near-maximal effort.

In this work, $F_"mech" (t)$ represents *single-source* thrust.
It may correspond to fin propulsion or arm/rope traction depending on discipline,
but not a simultaneous mixture.
Accordingly, force-cap parameters are mode- and discipline-specific.
For the remainder of this manuscript, we use a cap of $F_"mech"^"max" approx$ #qty[200][N] unless otherwise noted.

*Empirical Scale for Mechanical Power.*
Swimming measurements also bound plausible external mechanical power.
Reported values for front crawl span roughly $approx$ 26--108 #unit[W] across speeds and swimmers @toussaint1990mechanical.
Separately, peak oxygen uptake in incremental tethered swimming tests is commonly
$approx$ 2.7--3.7 #unit[L/min] @bonen1980maximal, corresponding to a maximal metabolic power of order $approx$ 1--1.3 #unit[kW].
With gross efficiencies $eta approx$ 0.05--0.095, this implies that sustained external mechanical power on the order of $approx$ 50--120 #unit[W] is physiologically reasonable, while higher values, if achievable, are necessarily brief.
For the remainder of this manuscript, we use a cap of $P_"mech"^"max" approx$ #qty[200][W] unless otherwise noted.

=== Metabolic Budgets and Effort Measures <sec:metabolic-budgets>

The metabolic-rate model defines instantaneous usage rates for each modeled resource.
Feasibility is determined by integrating these rates over the full dive duration, and comparing accumulated usage against the diver's quasi-constant budgets at the snapshot time of interest.

*Accumulated Usage.*
For a dive of dive time $T$, define accumulated oxygen consumption and #CO2 generation:

$
R_#O2 (T) := integral_0^T dot(V)_#O2 dif t,
quad
R_#CO2 (T) := integral_0^T dot(V)_#CO2 dif t.
$ <eq:O2CO2-int>

If additional constraints are modeled, index all resource quantities by $r$; the same feasibility and effort definitions apply.

*Budgets and Feasibility.*
Let $R_#O2^"total"$ denote the diver's usable oxygen store, and let $R_#CO2^"total"$ denote
the diver's effective #CO2 tolerance budget.
A dive is feasible if all modeled constraints are satisfied:

$
R_#O2 (T) <= R_#O2^"total"
quad "and" quad
R_#CO2 (T) <= R_#CO2^"total".
$ <eq:feasible-dual>

Uniformly scaling the total usable oxygen reserve rescales all oxygen consumption terms, so the feasibility boundary and performance frontier are invariant to that scale and depend only on relative oxygen usage rather than absolute #O2 volume.

*Effort Fractions and the Active Limiter.*
Define effort fractions as normalized usages:

$
E_#O2 := frac(R_#O2 (T), R_#O2^"total"),
quad
E_#CO2 := frac(R_#CO2 (T), R_#CO2^"total").
$ <eq:effort-O2CO2>

Under the first-fail interpretation, the dive terminates when the first constraint saturates.
Maximal dives therefore typically satisfy

$
max(E_#O2, E_#CO2) = 1,
$ <eq:effort-max>

and the resource attaining the maximum is the active limiter.

*Known Limiter in Practice.*
In practice, the dominant limiter is often known in advance for a given diver and training phase.
For example, elite depth specialists are commonly expected to be primarily #O2 limited, while less-adapted divers may terminate earlier due to #CO2 intolerance.
Accordingly, we treat one resource as the expected active limiter and verify that the other remains slack (i.e., $E_#O2 < 1$ or $E_#CO2 < 1$ at termination).

= Performance Frontier in Freediving <sec:performance-frontier-td>

== Dive Profiles as Elements of the T–D Diagram

We summarize each dive by two observables.
The $x$-axis is the total dive time $T$.
The $y$-axis is the maximum depth $D := max_(t) z(t)$, as shown in @fig:td-diagram.
The T–D plot uses an inverted $y$-axis: $D = 0$ is at the top, and larger depths appear lower.

#figure(
  image("../../images/td-diagram.pdf"),
  caption: [
    *Dive Time–Depth (T–D) Diagram with Representative Dives and Feasible Regions.*
    Each gray point is a recorded dive summarized by total time $T$ (x-axis) and maximum depth $D$ (y-axis, inverted); the dataset consists of my own dive logs collected over roughly two years using a Mission One watch from Atmos, covering every dive across 110+ sessions and totaling over 1,800 dives.
    Larger colored markers denote representative training modes (personal best dive in FIM, slow depth work in FIM, sprint dives in CWTB, and STA at $D=0$), and the shaded regions summarize the data-derived feasible and infeasible regions under the same conditions.
    The light green band marks empirically feasible dives, while the light red shading indicates dives that are not observed in the logs and are treated as infeasible under the same conditions.
    The diagram makes explicit how different dive profiles map to distinct regions of $(T, D)$ space and motivates the notion of a performance frontier.
  ],
  placement: top,
) <fig:td-diagram>

A *dive profile* in this paper is the time history of the diver's self-generated thrust, represented by the raw mechanical force $F_"mech" (t)$.
Together with the initial conditions, the force history $F_"mech" (t)$ induces a trajectory $z(t)$ and $v(t) = dot(z)$ through the dynamics @eq:eom-reparam-k, while remaining within the instantaneous capacity limits @eq:cap-constraints.
Physiological costs are accumulated by the metabolic rate model @eq:odot and are feasible only if the integrated budgets remain below their limits, equivalently $max(E_#O2, E_#CO2) <= 1$ via @eq:effort-O2CO2.

Because $F_"mech" (t)$ is a function of time, there are infinitely many feasible dive profiles even for a fixed target depth.
Each feasible profile produces exactly one point $(T, D)$ on the dive time–depth (T–D) diagram, and the collection of such points forms the basic "elements" of the diagram.

It is useful to anchor this abstract mapping with concrete training examples.
In my instructor course, constant weight with bi-fins (CWTB) and free immersion (FIM) dives were performed near personal best (PB) capability, which corresponded to points near the deepest feasible depth in the T–D diagram for that diver.
In my training logs, prescribed "slow" dives around #qty[30][m] emphasize time spent at depth and controlled pacing, producing points with comparatively large $T$ at a moderate $D$.
Static apnea (STA), such as a #qty[4][min] requirement in my course, maps to the degenerate depth $D = 0$ with very large $T$, placing it far toward the upper-right of the diagram when considered as a limiting breath-hold case.

Many common practice sessions fill in other parts of the plane even when they are not explicitly emphasized by certification standards.
For example, fast down-and-up sprints to about #qty[20][m] create points with small $T$ at modest $D$, and these lie close to the boundaries of the feasible region.
These examples illustrate the central idea.
A training prescription is not merely a "depth target" or a "time target."
It is a choice of dive profile, and that profile becomes a single point on the T–D diagram.
Selected dive profiles illustrating these representative points are shown in @fig:dive-profiles, and the same dives are highlighted as colored markers in @fig:td-diagram.

#figure(
  image("../../images/dive-profiles.pdf"),
  caption: [
    *Representative Dive Profiles Underlying Points in the T–D Diagram.*
    Each curve shows depth versus time for a single dive, drawn directly from my personal dive logs, including a personal best dive (FIM), a slow depth emphasis dive around #qty[30][m] (FIM), a sprint dive to about #qty[20][m] (CWTB), and a static apnea (STA) trace at $D=0$.
    Although these profiles can have similar depths, their pacing and time-at-depth differ substantially, which is why they occupy different locations in the T–D plane.
    The profiles visually ground the mapping from a full trajectory $z(t)$ to the summary point $(T, D)$ used in the frontier analysis.
  ],
  placement: top,
) <fig:dive-profiles>

== Feasible Region and Performance Frontiers

Sweeping across many feasible dive profiles produces a scattered plot of points in the dive time–depth (T–D) diagram.
This scattered plot is not noise.
It is the geometric footprint of what the diver can physically and physiologically realize under a fixed diver state and model parameters.

Formally, a dive is feasible if there exists a force history $F_"mech" (t) in cal(F)$ that induces a trajectory $z(t)$ via the dynamics @eq:eom-reparam-k, where $cal(F)$ is the set of all force histories that respect the instantaneous capacity limits @eq:cap-constraints, and satisfy the metabolic budgets through $max(E_#O2, E_#CO2) <= 1$ in @eq:effort-O2CO2.
Each feasible profile maps to one point $(T, D)$, so the set of all such points forms a *feasible region* in the T–D plane for that diver as illustrated in @fig:td-diagram.

Within this region, certain points are special.
For a fixed depth $D$, some profiles achieve that depth and return in the least possible time, while others stretch the dive time as long as possible without violating feasibility.
These two extremal envelopes define what we call the performance frontier in the T–D diagram.

- *Fast Frontier.*
  For each depth $D$, define $T_"fast" (D) := min_(F_"mech" (t) in cal(F)) T$ subject to $max_(t) z(t) = D$, where $z(t)$ is the trajectory induced by $F_"mech" (t)$ via @eq:eom-reparam-k and the instantaneous force and power limits in @eq:cap-constraints are satisfied under set $cal(F)$.
  This definition selects the lower envelope in @fig:td-diagram and corresponds to the fastest feasible completion at each depth.

- *Slow Frontier.*
  For each depth $D$, define $T_"slow" (D) := max_(F_"mech" (t) in cal(F)) T$ subject to $max_(t) z(t) = D$, under the same feasibility conditions as above.
  This definition selects the upper envelope in @fig:td-diagram and corresponds to the slowest feasible completion at each depth.

The fast and slow frontiers are empirical objects in the scattered plot, but they are also well-posed targets for theory.
If the model and coefficients are accurate, forward simulation and optimization should reproduce the observed envelopes as functions $T_"fast" (D)$ and $T_"slow" (D)$.
Conversely, systematic deviations between predicted and observed envelopes indicate which constraints or cost terms require refinement.
The theoretical derivations for both frontiers are given in the appendix at @sec:appendix-frontier-solvers.

A diver-specific maximum depth $D_"max"$ is implicit in the same picture.
It is the largest depth for which any feasible point exists in the T–D region under the diver's parameters and constraints.
Both frontiers are defined on $D in [0, D_"max"]$, and the feasible region vanishes for $D > D_"max"$.

== Analytical Optimization

We have defined the feasible region and the fast/slow frontiers from data, and now turn to deriving these frontiers from the governing equations in an analytical way.
This part states the modeling assumptions and outlines the common structure used to obtain closed-form or semi-analytic frontiers, while the full derivations are deferred to @sec:appendix-frontier-solvers.
The proxy families used in the remainder of this paper are introduced here as practical analytical surrogates for the full optimization problems.

=== Modeling Premises <sec:frontier-modeling-premises>

To obtain tractable frontier calculations, we adopt the following premises:

*Quasi-Steady Vertical Mechanics.*
We use the re-parameterized equation of motion @eq:eom-reparam-k and work in the drag-dominated regime where $m dot(v)$ is small compared with the other terms except near the turn.

*Single-Turn Geometry.*
A dive consists of one descent segment to a maximum depth $D$ and one ascent segment back to the surface.
The depth is monotone within each segment.

*Aligned Thrust.*
The diver generates thrust aligned with the direction of travel.
We represent the control by the thrust magnitude $f(t) := abs(F_"mech" (t)) >= 0$ with direction handled by the phase (descent vs ascent).
Thus $F_"mech" (t) = +f(t)$ on descent and $F_"mech" (t) = -f(t)$ on ascent under the stated sign convention.
Equivalently, we have $F_"mech" (t) = f(t)$ on descent and $F_"mech" (t) = -f(t)$ on ascent.

*Hard Instantaneous Limits.*
The force and power capacity limits are enforced pointwise through @eq:cap-constraints.
When a frontier solution would exceed those limits, the control saturates at the active constraint.

*Budget Model.*
Frontier computations in this section are presented under an oxygen-limited approximation, using $E_#O2 <= 1$ as the active integrated constraint from @eq:effort-O2CO2.
The full two-budget feasibility condition $max(E_#O2, E_#CO2) <= 1$ remains the definition of feasibility, and can be re-enabled by adding a second budget constraint without changing the mechanical derivations.
We assume the #CO2 constraint is non-binding in the analyzed regimes, consistent with the selected dive profiles and depth ranges.

=== Frontier Computation as Constrained Optimization

For a fixed target depth $D$, a dive profile is *feasible* if there exists a thrust history $F_"mech" (t)$ that reaches $max_(t) z(t) = D$ while respecting the instantaneous capacity constraints @eq:cap-constraints and the metabolic budgets @eq:effort-O2CO2.
With the oxygen-limited approximation, we write the budget constraint as $R_#O2 (T) <= R_#O2^"total"$.

Rather than enumerating "all possible" dive profiles, we cast the boundary of feasibility as a constrained optimization problem.
This yields two canonical envelopes in the T–D diagram: a *minimum-time* envelope (fast frontier) and a *maximum-time* envelope (slow frontier).

The fast frontier is the minimum-time solution under these constraints.

$
T_"fast" (D)
:= min_(F_"mech" (t) in cal(F)) T
quad
"s.t."
quad
max_(t) z(t) = D,
quad
R_#O2 (T) <= R_#O2^"total".
$ <eq:fast-frontier-opt>

Here $cal(F)$ denotes the set of force histories respecting @eq:cap-constraints and the mechanics @eq:eom-reparam-k.
The key design choice is to avoid solving this as a full-blown optimal control problem in time.
Under the quasi-steady premise and monotone descent/ascent, the objective and budget can be written in depth coordinates, and the constrained problem admits an analytic characterization through a single Lagrange multiplier.
In practice, this turns "optimize a function of time" into a one-dimensional multiplier search (budget tightening) wrapped around many small one-dimensional thrust minimizations, as summarized in @sec:appendix-fast-frontier.

A second design choice is *parameter inference by stages*.
Instead of treating all coefficients as free at once, we anchor the model with measurements (e.g., $z_n$, $v_oo$, and capacity proxies), then calibrate remaining physiological and capacity parameters against logged dives and a small number of reference performances.
This makes the frontier computation a forward map $theta -> (T_"fast" (D), T_"slow" (D))$ once $theta$ is fixed, which is crucial for subsequent fitting and planning.

The slow frontier is the maximum-time solution under the same constraints.

$
T_"slow" (D)
:= max_(F_"mech" (t) in cal(F)) T
quad
"s.t."
quad
max_(t) z(t) = D,
quad
R_#O2 (T) <= R_#O2^"total".
$ <eq:slow-frontier-opt>

Computationally, the slow frontier reuses the same machinery as the fast frontier.
Maximizing $T$ under a budget is equivalent to minimizing $(-T)$ under the same budget, which corresponds to a sign flip in the time term inside the Lagrangian while leaving the constraint structure unchanged.
This "same solver, sign flip" symmetry is what makes it practical to compute both envelopes consistently from the same reduced model, as detailed in @sec:appendix-slow-frontier.

= Applications and Discussions <sec:applications-and-discussions>

== Example Performance Frontier <sec:example-performance-frontier>

This subsection illustrates the T–D diagram as a practical object, by overlaying a diver's recorded dives (from the author's personal training log) with a pair of theoretical envelope curves computed from a single calibrated parameter set.
Each dive profile maps to one point $(T, D)$, and the collection of points forms an empirical feasible cloud.
Given a fixed model and parameters, the same constraints induce a *predicted* feasible band whose left and right edges are the fast and slow frontiers.

#figure(
  image("../../images/frontiers.pdf"),
  caption: [
    *Sample Fast and Slow Performance Frontiers.* Gray points show the author's recorded dives plotted by total dive time $T$ (x-axis) and maximum depth $D$ (y-axis, inverted so deeper dives appear lower).
    The shaded green band indicates the model-predicted feasible region between the theoretical fast frontier (dashed) and slow frontier (dotted), while the red shading indicates infeasible $(T, D)$ pairs under the same parameter set and assumptions.
    The two envelopes meet at the modeled maximum depth, beyond which no feasible round-trip exists under the specified budgets and instantaneous limits.
  ],
  placement: top,
) <fig:example-frontier>

We compute the two envelope curves in @fig:example-frontier using the frontier solver described in the previous subsection, holding the diver (the author)'s state and coefficients fixed.
For transparency, the example uses the following user-facing parameter values:
These parameters are effective calibrated quantities rather than direct measurements of physiological primitives.
- neutral depth: $z_n = #qty[12][m]$,
- failure depth: $z_"failure" = #qty[30][m]$, where $z_"failure"$ denotes the depth at which a fully inhaled lung at the surface would be compressed to the residual volume,
- terminal speed scale: $v_oo = #qty[0.80][m/s]$,
- static reference time: $T_"STA" = #qty[240][s]$, where $T_"STA"$ is the measured static apnea duration used as an empirical calibration reference,
- vital capacity: $V_"VC" = #qty[5.0][L]$.

These inputs imply several derived quantities used internally by the reduced mechanics and oxygen budget:
- total gas volume at surface (using total lung capacity, i.e., VC + residual volume): $V_("gas", 0) = #qty[6.7][L]$,
- basal oxygen consumption: $dot(V)_(#O2,"rest") = #qty[7.0][mL/s]$,
- drag constant: $k = #qty[48][N/(m/s)^2]$.
This $k$ is an effective lumped drag constant and can exceed estimates from static $C_d$ and $A$ alone because it absorbs fins, posture, oscillatory motion, equipment, and discipline-specific technique.

These numerical oxygen quantities are expressed under the chosen normalization of usable oxygen; alternative assumptions about total usable oxygen would rescale the absolute values without affecting relative consumption, feasibility, or conclusions.
Static apnea provides an integrated calibration anchor, while dynamic dive costs are extrapolated under the same normalized oxygen budget with differences absorbed into the effective basal, alpha, and beta terms.

The parameters are adjusted so that the recorded dive points are predicted to be feasible under the model, i.e., the cloud lies (up to noise and unmodeled variation) within the feasible band bounded by the two theoretical frontiers.
This is the fundamental consistency requirement before the theoretical frontier can be used as a diagnostic tool.
The frontier represents feasibility under the modeled assumptions rather than a guarantee of achievable performance, and deviations may arise from technique, psychological factors, or unmodeled physiology.
The comparison to recorded dives is intended as a qualitative plausibility check rather than an exact validation, since real performance is influenced by factors beyond the model.

The *shape* of the two envelopes is informative.
In this example, the fast frontier is approximately linear for shallow-to-moderate depths (roughly under #qty[20][m]) and becomes sublinear at larger depths as the ascent penalty grows and the oxygen budget begins to bind more tightly.
The slow frontier begins near the STA limit at very shallow depths, remains approximately linear down to about #qty[30][m], and then becomes sublinear and folds as depth increases, reflecting a shrinking feasible window in time as the modeled depth limit is approached.
In this calibrated example, the two frontiers meet near $D approx$ #qty[50][m] at around $T approx$ #qty[150][s], marking the predicted maximum depth attainable under the same conditions and constraints.

=== Resource Usage Along the Frontiers <sec:example-frontier-resource-usage>

Beyond the geometry of @fig:example-frontier, the theoretical frontiers also expose *which constraints are actually binding* at different depths.
@fig:frontier-resource-usage summarizes this by plotting
(i) peak force/power utilization and
(ii) the oxygen budget breakdown, each as a function of maximum depth, evaluated along the fast and slow frontiers.
This turns the frontier curves from "just envelopes" into an interpretable accounting of what limits the diver as depth increases.

#figure(
  image("../../images/frontier-usage.pdf"),
  caption: [
    *Resource Usage Along the Fast and Slow Frontiers.* The $y$-axis is maximum depth $D$ (inverted so deeper dives appear lower).
    *Left:* Peak mechanical force and peak mechanical power along the optimal profile, reported as a percentage of the corresponding constraint limit.
    *Right:* Oxygen budget shares (basal, activation, and mechanical), reported as percentages that sum to the total budget.
    Dashed curves correspond to the fast frontier (minimum-time envelope), and dotted curves correspond to the slow frontier (maximum-time envelope).
  ],
  placement: top,
) <fig:frontier-resource-usage>

Several practical patterns emerge.
First, the *fast frontier* exhibits a depth-dependent "active limiter."
At shallow depths (roughly below #qty[20][m] in this example), the fast frontier is primarily force/power limited: the optimal strategy is to push close to the instantaneous capacity caps to minimize time.
In this regime, the total oxygen usage approaches the full available budget even for relatively modest depths, which matches the subjective feel of all-out sprint dives where the constraint is not "can I stay longer," but "can I push harder without blowing up."
Above about #qty[20][m], the fast frontier becomes oxygen bound across depths: the solver must pace the thrust profile to ensure the integrated oxygen usage remains within $R_#O2^"total"$, and the peak force/power utilization decreases accordingly.
Operationally, this is where "sprint mindset" stops being feasible and the computed optimum shifts toward controlled pacing.

Second, the *slow frontier* is oxygen bound throughout the depth range shown.
This is consistent with the definition of the slow envelope as a maximum-time solution under an oxygen-limited budget: time itself becomes the expensive resource via the basal term.
Interestingly, the peak force and power utilization along the slow frontier remain relatively low and vary weakly with depth in this example, which aligns with common practice in hang / slow dives where the goal is not to produce large peaks but to travel gently to the target depth and manage the remaining budget by staying calm and efficient.

=== Frontier-Optimal Dive Profiles <sec:example-frontier-profiles>

The frontier curves in @fig:example-frontier summarize feasibility in the T–D plane, but the solver also produces *the corresponding optimal dive profiles* at each target depth.
@fig:fast-frontier-profiles and @fig:slow-frontier-profiles visualize these profiles as time series of depth, speed, and thrust for a representative set of depth targets.
In both figures, each panel corresponds to a fixed target depth $D$, the x-axis is elapsed dive time, the left y-axis is depth (inverted), and the right y-axes show vertical speed and thrust.
All panels use an aligned time axis range so the duration scales are directly comparable across depth targets.

#figure(
  image("../../images/frontier-profiles-fast.pdf", height: 85%),
  caption: [
    *Fast-Frontier Optimal Dive Profiles (Depth, Speed, Thrust, and Oxygen Usage).* Each panel shows the minimum-time round trip to a target depth $D$ under the same instantaneous force / power caps and the oxygen-budget constraint.
    Depth exhibits a characteristic V-shape, speed changes sign at the turn, and thrust is continuously modulated with a sharp sign flip between descent and ascent; the fourth axis reports cumulative oxygen usage as a percentage of the budget.
    The elapsed-time axis is aligned across panels to make duration comparisons across depths visually meaningful.
  ],
  placement: top,
) <fig:fast-frontier-profiles>

#figure(
  image("../../images/frontier-profiles-slow.pdf", height: 85%),
  caption: [
    *Slow-Frontier Optimal Dive Profiles (Depth, Speed, Thrust, and Oxygen Usage).* Each panel shows the maximum-time pacing strategy to the same target depths $D$ under the oxygen-budget constraint and the same instantaneous caps.
    As in the fast case, depth follows a V-shape and both speed and thrust switch sign at the turn, but the pacing differs markedly in how thrust is allocated over depth and time; the fourth axis reports cumulative oxygen usage as a percentage of the budget.
    The elapsed-time axis is aligned across panels to make duration comparisons across depths visually meaningful.
  ],
  placement: top,
) <fig:slow-frontier-profiles>

Several qualitative features are shared across both frontiers.
Across all depths and both envelopes, the depth trajectory is approximately V-shaped, speed transitions from positive to negative at the turning point, and thrust is continuously modulated with a sharp sign change that reflects the descent-to-ascent transition.

The fast-frontier profiles in @fig:fast-frontier-profiles highlight how the optimizer uses thrust to minimize round-trip time under the constraints.
A notable pattern is that the descent speed approaches a depth-limited terminal scale (about #qty[0.8][m/s] in this example) at greater depths, while becoming progressively slower in shallow water where buoyancy is more positive and the diver must "pay" for downward progress.
In addition, the thrust does not generally drop to zero over the deep segment, except in the deepest attempt where thrust relaxes after roughly #qty[20][m], which coincides with the practical "freefall" intuition even though the model is solved as a continuous constrained optimum.

The slow-frontier profiles in @fig:slow-frontier-profiles show a distinct "shark-fin" structure in speed.
Near and above neutral depth, the diver slows and then transitions into a low-thrust regime where the descent becomes increasingly assisted and speed gradually picks up until the turn.
After the turn, the diver applies strong upward thrust early on when the buoyancy penalty is largest, then progressively relaxes thrust as the diver approaches shallow water where buoyancy contributes more to the return.
This pattern is especially interesting because it coincides with mainstream dive planning heuristics in a qualitative sense, while still being derived from the same constrained optimization framework used to compute the theoretical frontiers.

Comparing the two sets of frontiers, they are identical when the depth target is the maximum feasible depth $D_"max"$, where both envelopes converge to the same point.
From a training standpoint, the frontier-optimal profiles also suggest that *pace shaping* matters at least as much as "raw effort."
In particular, the slow-frontier profile tends to avoid "wasting" effort on early acceleration above (or near) neutral depth and instead modulates thrust so that the resulting speed stays more nearly constant over long segments, reserving higher output for the portions where the model predicts it has the largest marginal benefit (e.g., early ascent when buoyancy penalty is strongest).
This nuance pushes back on the simplistic heuristic of "rush through the top as fast as possible," because an unnecessary sprint near the surface can burn extra activation / mechanical cost without meaningfully improving feasibility at the target depth.
Practically, this motivates drills that target *controlled, depth-dependent pacing* (especially around the neutral-depth transition) rather than training only for peak speed or peak thrust in isolation.

=== Performance Bands by Effort Level <sec:effort-bands>

#figure(
  image("../../images/frontiers-efforts.pdf"),
  caption: [
    *Frontiers by Effort Level.* The same T–D diagram as @fig:example-frontier, but stratified by effort fraction.
    Each colored band corresponds to dives whose modeled total effort $E$ falls within a fixed percentage range of the diver's full budget (e.g., 0--20%, 20--30%, …, 90--100%).
Lower-effort feasible sets are nested inside higher-effort sets, and the outer boundary (90--100%) approaches the full theoretical performance frontier.
    Gray points are recorded dives.
  ],
  placement: top,
) <fig:effort-bands>

@fig:effort-bands makes explicit that the feasible region is not a binary "possible vs. impossible" set, but a family of nested regions indexed by the fraction of the total budget one is willing to spend for a single dive.
Operationally, this is computed by scaling the total store budget and re-solving the same constrained frontier problem, producing a stratified map of "how deep / how long" at a given effort level.

This visualization also clarifies the distribution of real training dives relative to the model.
Most recorded dives cluster in low-to-moderate effort bands, indicating substantial headroom in typical sessions and explaining why many dives feel routine despite being spread across a range of depths and times.
In contrast, the outermost band near 90--100% represents the regime where the model predicts marginal feasibility, where small changes in conditions or pacing can push a plan across the boundary.

Finally, the effort bands help separate "maximum possible" from "prudent."
The deepest or longest points on the outer envelope may be achievable, but they occupy a thin region where the margin for error is small and the implied risk is high.
Conversely, the interior bands form a broader, more stable region in which timing is more predictable and the feasibility classification is less sensitive, which is often the more useful regime for safety planning and repeatable training.

== Generalization <sec:generalization>

The same frontier construction can be repeated for multiple divers, using only (i) their logged dives and (ii) a diver-specific parameter set.
The purpose of this section is to show that the framework generalizes: once parameters are adapted, the *same* solver produces a feasible band whose envelopes are consistent with the empirical dive cloud, and the corresponding resource-usage plots explain which constraints dominate where.

=== Region-Level Champion Diver <sec:generalization-zx>

#figure(
  grid(
    columns: 2,
    image("../../images/zx.b.jpg", height: 175pt),
    image("../../images/zx.a.jpg", height: 175pt),
  ),
  caption: [
    *Region-Level Champion Diver.*
    *Left:* Casual portrait from a mountain hike. Taken from his social media. (Instagram: #link("https://www.instagram.com/jje2fu02")[\@jje2fu02])
    *Right:* Underwater camera showing his "dance" during a plastic bi-fin dive. Taken from competition host's social media. (Instagram: #link("https://www.instagram.com/cat._.fish_ocean")[\@cat.\_.fish_ocean])
  ],
  placement: top,
) <fig:generalization-zx>

The second subject (in addition to myself) is my instructor for the AIDA 2 and AIDA 3 courses.
He is famously known for using plastic bi-fins to dive to his then-near personal best of 58 m while still "performing" to the camera—literally dancing—during a regional competition.
His personal best records are CWTB #qty[69][m] and STA #qty[245][s], where these are official / recorded PBs and training or discipline-specific maxima may differ.

#figure(
  image("../../images/frontiers.zx.pdf"),
  caption: [
    *Performance Frontier for the Region-Level Champion Diver.*
    Gray points are the diver's recorded dives mapped onto the T–D diagram.
    The shaded background indicates the modeled feasible region under a diver-specific fitted parameter set, with the dashed curve marking the fast frontier (minimum time at each depth) and the dotted curve marking the slow frontier (maximum time at each depth).
    This figure serves as a containment check: the theoretical feasible band should envelope the empirical cloud up to expected noise, condition shifts, and logging variance.
  ],
  placement: top,
) <fig:generalization-zx-frontier>

#figure(
  image("../../images/frontier-usage.zx.pdf"),
  caption: [
    *Resource Usage Along the Region-Level Champion Diver's Frontiers.*
    *Left:* Peak force and peak power utilization as a percentage of the corresponding capacity limits, evaluated along the frontier-optimal profiles.
    *Right:* Oxygen budget shares (basal, activation, and mechanical) evaluated along the same profiles, shown separately for fast and slow envelopes.
    Together, these panels interpret @fig:generalization-zx-frontier by indicating which constraints bind at different depths and why the envelope deforms as it approaches the depth limit.
  ],
  placement: top,
) <fig:generalization-zx-usage>

Compared to my own profile, his calibrated parameters differ in a few notable ways.
His terminal speed scale is observed to be higher (about #qty[0.85][m/s]).
His static apnea reference time is #qty[245][s].
His vital capacity is close to mine.

In @fig:generalization-zx-frontier, the empirical dives populate a broad interior region while the deepest points approach the lower envelope near the modeled depth limit.
The overall picture mirrors the single-diver example: the feasible set forms a depth-dependent time band bounded by a fast envelope on the left and a slow envelope on the right.
The "right wall" (slow frontier) is much less densely sampled in typical training logs, which is expected in practice: divers often train within a comfort band and only occasionally probe near-maximal time-at-depth plans, especially at deeper targets.
At his PB dive, he self-reported feeling "slow," and the analysis is consistent with that report: he is roughly #qty[20][s] above the computed optimal (minimum-time) profile at that depth.

The resource-usage decomposition in @fig:generalization-zx-usage provides an intuitive explanation for the envelope shape.
As depth increases, the fast frontier transitions from being predominantly limited by instantaneous output (force / power caps) toward being limited by the integrated oxygen budget, reflecting the shift from "sprintable" shallow dives to paced deeper dives.
His leg drive is materially stronger than mine and his power limit is higher (#qty[250][W] compared to my #qty[200][W]), which translates into the ability to sustain sprint-style dives to greater depth.
He reported being able to sprint to around #qty[40][m] but being unable to complete a true #qty[45][m] sprint dive, which is highly consistent with the modeled transition implied by @fig:generalization-zx-usage.
Meanwhile, the slow frontier remains oxygen dominated across the depth range, consistent with its definition as a maximum-time solution: extending $T$ directly increases basal cost, and the optimizer therefore redistributes thrust to minimize unnecessary activation and mechanical expenditure while still reaching the target depth.

Across my own example and his example, we observed an interesting phenomenon: our STA times are similar, and the modeled dive time at maximum depth is also very similar (around #qty[150][s]).
This suggests a working hypothesis that "maximum dive time at depth" may land around ~65% of STA time across a range of skill levels, at least under oxygen-limited planning.
This further hints at a bolder hypothesis: given the AIDA instructor requirement of being able to perform a ~4 minute static apnea, an instructor's capacity might already be well prepared for at least #qty[50][m] to #qty[60][m] under the assumptions of this model and the conditions studied here.
These observations must be tested more carefully with additional divers and, ideally, with training interventions designed from the theory and evaluated by pre/post shifts of the fitted frontiers.

=== World-Class Perspective <sec:generalization-yu>

于志瀛 (Zhiying Yu) is a world-class freediver from China, holding multiple records across disciplines including (as of the time of writing) CWTB (#qty[88][m]) and FIM (#qty[112][m]).
He is one of the inspirations behind this topic.
In his #link("http://xhslink.com/o/5L5ntMLBFnk")[long-form reflection video] @yu2025divetime, on "dynamic time," he repeatedly returns to a theme that fits the present framework well: the raw dive time $T$ is an observable that matters, but it is not the *thing to optimize* in isolation.
He opens with a blunt disclaimer: "Dive Time可能是一个伪命题" ("dive time may be a pseudo-question"), and emphasizes "最终以个人感受为主" ("ultimately prioritize personal sensation").

#figure(
  image("../../images/yzy.jpg", width: 30%),
  caption: [
    于志瀛 (Zhiying Yu), in a training reflection video discussing "dynamic time," ascent bottlenecks, and the limited transfer between depth and pool dynamics.
    In this subsection, his qualitative observations are used as an external point of comparison for the theoretical notions of feasibility, constraint switching, and frontier-based proxy training.
  ],
  placement: top,
) <fig:generalization-yu>

This viewpoint aligns directly with the role of the T–D diagram in our theory.
The diagram uses $T$ as an axis because it is measurable and operational, but feasibility is governed by integrated budgets and constraints, not by time alone.
This is also why we later interpret the frontier not only by its geometric envelope on the T–D plane, but also by the corresponding constraint usage (force, power) and oxygen budget decomposition.

*Constraint Switching and the Ascent Bottleneck.*
A central thread in Yu's reflection is that his limiting factor is the ascent: "最大的问题跟短板是回程的速度慢" ("my biggest problem and shortcoming is a slow return speed"),with ascent speeds described around 0.6--0.7 #unit[m/s], while elite male divers often ascend at 0.9--1.0 #unit[m/s].
In frontier language, this is a clean example of constraint switching.
At shallow depths, a diver may remain largely instantaneous-capacity limited (force / power), but as depth increases, ascent becomes a regime where drag and buoyancy must be paid continuously, and the solution becomes much more sensitive to ascent-side capacity and oxygen spending.
The model therefore predicts exactly the lived experience: descent can remain comfortable while the ascent becomes the binding constraint that bends the fast frontier rightward (larger $T$ for the same $D$).
As @fig:slow-frontier-profiles shows in its last panel, when in max-performance dives, the descent takes about ~40% of the budget only, and this aligns well with his feelings.

*Why Dive Time Can Appear "Discipline-Invariant."*
Yu reports an interesting regularity: "我的dive time不受项目所影响" ("my dive time is not affected by the discipline"), describing how different disciplines converge to a similar end-stage sensation as he approaches PB-level dive time.
Below is a list of his self-reported dives in training sessions for reference:
- CNF: #qty[76][m] in #qty[250][s],
- FIM: #qty[106][m] in #qty[263][s], and 
- CWTB: #qty[96][m] in #qty[249][s].

Within our framework, this can happen when a single global limiter dominates across disciplines for that diver.
These data points, as compared to his personal best in STA at #qty[402][s], falls in the 60--65% range, matching exactly what is hypothesized in this work.

If the decisive bottleneck is "how much usable oxygen budget remains by the time ascent becomes expensive," then different propulsion styles can still converge to similar total times, even if the local mechanics and subjective feel differ during the dive.
This gives a principled explanation for why a diver can experience time as discipline-invariant while still having discipline-specific technical weaknesses.

*Training Implications and Why Proxy Frontiers Are Attractive.*
Finally, Yu frames his own development as partly accidental: he describes having used a clumsy method, i.e., repeatedly pushing PB dives and being forced to adapt, and then asks whether a safer approach exists: converting some deep forced hypoxia exposure into safer, more controllable shallow-depth hanging practice.
This question is precisely the practical motivation for proxy frontiers in this paper.
A hang-style slow-frontier proxy concentrates oxygen-budget stress while reducing mechanical risk and logistical variability, and it is much easier to parameterize and repeat, which matters both for training design and for fitting diver-specific coefficients from logs.

Taken together, Yu's narrative supplies an external qualitative check on the theory.
He independently highlights (i) the limitation of treating dive time as the sole objective, (ii) a depth-dependent shift in what binds performance (often ascent-side), and (iii) the value of safer proxy protocols to target the relevant budget, all of which are structural features of the feasibility-and-frontier view developed here.

#pagebreak()

= Conclusion

This work introduces a formal, physics-to-physiology framework for understanding freediving performance through the lens of a *performance frontier*.
Rather than treating "best performance" as a single scalar metric, we define performance as a feasible region in the $(T, D)$ plane—total dive time $T$ versus maximum depth $D$—and characterize its boundary via fast and slow frontier envelopes.
By combining hydrodynamics, body forces, motion constraints, and resource-limited physiological cost modeling, the frontier becomes a well-posed computational object: it can be derived from explicit assumptions, solved via quantitative tools, and interpreted mechanistically.

A key contribution is that the framework is not purely theoretical.
We show how to instantiate and calibrate the model using data from real freedivers, yielding diver-specific feasible regions and frontier predictions.
Model parameters—such as effective drag, force and power limits, and effective metabolic cost terms—become quantitatively constrained proxies that tether the theory to observed performance, enabling meaningful comparison across divers, disciplines, and training states.

Beyond prediction, the frontier acts as a diagnostic instrument.
Many commonly reported freediving phenomena emerge naturally as *constraint switching* across depth and pacing regimes: different portions of the frontier become limited by different combinations of mechanics and physiological budgets.
This perspective reframes "what limits the dive" from a qualitative intuition into a structured question: which constraints bind, where, and by how much?
Importantly, although absolute oxygen stores and consumption rates cannot be directly measured with high fidelity—especially under apnea—the framework remains operational by treating oxygen usage in relative, budget-normalized terms. Under this normalization, conclusions about feasibility, regime transitions, and training leverage remain interpretable even when absolute compartment accessibility is uncertain.

Finally, the framework provides actionable training guidance that aligns with expert, experience-based heuristics while making their implications explicit and testable.
The model identifies concrete levers for expanding feasible performance—reducing effective drag, increasing available thrust capacity within force/power limits, improving efficiency terms that penalize mechanical work, and shaping pacing/effort allocation across descent and ascent.
In this way, the performance frontier unifies explanation and intervention: it offers a quantitative map from observed dive behavior to limiting mechanisms and to targeted training directions, enabling a more systematic and individualized approach to improving freediving performance.
